steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run-script', 'build' ]
  - name: 'gcr.io/lakwatsaya-app/firebase'
    args: [ 'deploy', '--project', 'lakwatsaya-app']
    secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: projects/lakwatsaya-app/locations/global/keyRings/firebase-keyring/cryptoKeys/firebase-key
  secretEnv:
    FIREBASE_TOKEN: 'CiQAfFG5WJSD908YsRJS7qWMEVQy+8d5javagf76EcTk29NRslwSVgCcvqQjInZ4O8mTbaAd5izSG49NErMdwyClw89ir9Gfypzhzy6FWCC1XlFyj3g9g11UUEOLvYMJFkke7w4locYgJEd1SwLhiAHMsAyiePCwn+xqLdE7'